[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.complete-check]
dependencies = [
  "format",
  "check",
  "clippy",
  "test",
  "code-coverage",
  "docs",
  "build",
  "audit-flow",
  "outdated-flow",
]

[tasks.code-coverage]
workspace = false
install_crate = "cargo-tarpaulin"
command = "cargo"
args = [
  "tarpaulin",
  "--exclude-files=target/*",
  "--out=html",
  "--output-dir=coverage",
  "--skip-clean",
  "--target-dir=target/tarpaulin",
]

[tasks.book]
workspace = false
install_crate = "mdbook"
command = "mdbook"

[tasks.clean-book]
extend = "book"
args = ["clean", "hooked-book"]

[tasks.build-book]
extend = "book"
dependencies = ["clean-book"]
args = ["build", "hooked-book"]

[tasks.serve-book]
extend = "book"
dependencies = ["clean-book"]
args = ["serve", "hooked-book"]

[tasks.deploy-book]
workspace = false
dependencies = ["build-book"]
command = "netlify"
args = ["deploy", "-d", "hooked-book/book/html", "-p", "-s", "holllo-hooked"]
