[book]
authors = ["Holllo"]
language = "en"
multilingual = false
src = "source"
title = "Hooked"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://git.bauke.xyz/Holllo/hooked"

[output.linkcheck]
